name: Build & deploy function

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths-ignore:
    - 'src/Shared/**'
    - 'README.md'
    - 'doc/**'
    - 'test/**'

jobs:
  build-service:
    uses: ./.github/workflows/.script-build-service-docker-image-and-push-into-acr.yml
    with:
      ENVIRONMENT_TYPE: demo
      PROJECT_NAME: cloudtrack
      SERVICE_NAME: regstr-func
      DOCKERFILE_PATH: ./src/CloudTrack.Registration.NumberAssignatorAzFunction/Dockerfile
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      NUGET_PASSWORD: ${{ secrets.NUGET_TOKEN }}

  deploy-service:
    uses: ./.github/workflows/.script-deploy-service-into-aca.yml
    needs: build-service
    with:
      ENVIRONMENT_TYPE: demo
      RESOURCE_GROUP: ${{ vars.AZURE_GROUP }}
      PROJECT_NAME: cloudtrack
      SERVICE_NAME: regstr-func
      RESOURCE_PREFIX: func
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
